name: test
on:
  pull_request:
    branches: main

jobs:
  diff:
    name: Check file changes
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
       with: 
         ref: ${{ github.event.pull_request.head.sha }}
     - name: Count non-txt file changes except module3
       id: diff-non-txt
       uses: tj-actions/changed-files@bfc49f4cff6934aa236c171f9bcbf1dd6b1ef438 # v40.0.1
       with:
         files: |
         **
         module3/**/*.txt
         files_ignore: "**/*.txt"
     - name: List all changed files except for .txt files outside module3
       run: |
         for file in ${{ steps.diff-non-txt.outputs.all_changed_files }}; do
           echo "$file was changed"
         done
